package io.github.youndie.kompot.forms

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass
import io.github.youndie.kompot.KompotAction

// The serialisation "plugin" for form actions. The components themselves carry
// @KompotComponentMarker (see Components.kt) and their polymorphic registration is generated by
// :kompot-registry-processor into generatedFormsSerializersModule.
val kompotFormsSerializersModule =
    SerializersModule {
        polymorphic(KompotAction::class) {
            subclass(SubmitFormAction::class)
        }
    }
