package io.github.youndie.kompot.standard

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass
import io.github.youndie.kompot.KompotAction

// The serialisation "plugin" for the standard components' actions. The components themselves carry
// @KompotComponentMarker (see Components.kt and Pagination.kt) and their polymorphic registration is
// generated by :kompot-registry-processor into generatedStandardSerializersModule. Actions fall
// outside that annotation's scope and stay registered by hand.
val kompotStandardSerializersModule =
    SerializersModule {
        polymorphic(KompotAction::class) {
            subclass(NavigateAction::class)
            subclass(CopyTextAction::class)
            subclass(CloseAction::class)
            subclass(LoadPageAction::class)
        }
    }
