package io.github.youndie.kompot.spec

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * TypeScript declarations for the wire, printed from the schema documents (SPEC.md §15) — for a
 * reading side that is not Kotlin, which otherwise retypes by hand what the schema already says and
 * drifts from it without a word.
 *
 * Every `$defs` entry becomes a type of the same name. The hierarchies come from the profile, which
 * lists every variant the build has; an OPEN hierarchy (`KompotComponent`, `KompotAction`) is the union
 * of those variants PLUS an unknown branch with `type: string`, because the protocol promises a client
 * types it has never seen (§2.1). Declaring the union closed would promise what the wire does not —
 * and a `switch` on `type` that looks exhaustive would be wrong at the first newer server.
 *
 * Patterns (`pattern`, `not`) have no TypeScript form and stay `string`; the schema still checks them.
 *
 * [strict] prints every hierarchy CLOSED — no unknown branch. That is the writing side's file: a
 * server building a body means one of the types it names, and TypeScript cannot say "any string but
 * these", so an unknown branch with `type: string` would accept every mistake as a type it does not
 * know (a `row` with `"spacing": "wide"` is a perfectly good unknown node). Reading side: the open
 * file; writing side: the strict one.
 */
public object TypeScriptDeclarations {
    public fun render(
        documents: Map<String, JsonObject>,
        strict: Boolean = false,
    ): String {
        val profile = documents[KompotProtocol.PROFILE_FILE_NAME]?.get("\$defs")?.jsonObject ?: JsonObject(emptyMap())
        val modules = documents.filterKeys { it != KompotProtocol.PROFILE_FILE_NAME }.toSortedMap()

        // Open or closed is said by the base definition (kompot-core); the full list of variants by the
        // profile. The profile marks every hierarchy closed for ITS build, which is not what a reader
        // of the wire may assume.
        val openHierarchies =
            modules.values
                .flatMap { (it["\$defs"]?.jsonObject ?: JsonObject(emptyMap())).entries }
                .filter { (_, def) -> def.jsonObject.kind() == "hierarchy" && def.jsonObject["x-kompot-open"]?.jsonPrimitive?.content == "true" }
                .map { it.key }
                .toSet()
                .takeUnless { strict } ?: emptySet()

        // What a variant inherits from its hierarchy's base definition: the properties every node of the
        // hierarchy may carry whatever its type (a component's `fallback`, SPEC.md §2.1). The variant's
        // own schema lists only what its Kotlin class declares, and TypeScript refuses a property an
        // object literal's type does not name — so without this a writer could not put on a node the
        // one key the protocol asks it to write for every new type.
        val baseProperties =
            modules.values
                .flatMap { (it["\$defs"]?.jsonObject ?: JsonObject(emptyMap())).entries }
                .filter { (_, def) -> def.jsonObject.kind() == "hierarchy" && def.jsonObject["properties"] != null }
                .associate { (name, def) -> name to def.jsonObject["properties"]!!.jsonObject }
        val inherited =
            profile.entries
                .flatMap { (hierarchy, def) ->
                    val base = baseProperties[hierarchy] ?: return@flatMap emptyList()
                    (def.jsonObject["oneOf"]?.jsonArray ?: JsonArray(emptyList())).map { typeOf(it) to base }
                }.toMap()

        val out = StringBuilder()
        out.appendLine("// Generated by TypeScriptDeclarations from kompot-spec/schema — do not edit by hand.")
        out.appendLine(
            if (strict) {
                "// STRICT: every hierarchy closed — for the side that WRITES bodies. Readers use kompot.d.ts."
            } else {
                "// OPEN: KompotComponent and KompotAction admit types this build does not know — for the side that READS bodies."
            },
        )
        out.appendLine("// Regenerate with KOMPOT_SPEC_RECORD=true ./gradlew :kompot-spec:test")
        out.appendLine()

        modules.forEach { (fileName, document) ->
            val defs = document["\$defs"]?.jsonObject ?: return@forEach
            out.appendLine("// ${fileName.removeSuffix(".schema.json")}")
            out.appendLine()
            defs.forEach { (name, element) ->
                val def = element.jsonObject
                // A hierarchy the profile lists is printed once, from the profile, below. One it does not
                // list — the closed modifier chain, the wizard's transitions — is printed here, from
                // its own oneOf.
                if (def.kind() == "hierarchy" && name in profile) return@forEach
                out.append(if (def.kind() == "hierarchy") hierarchy(name, def, open = name in openHierarchies) else declaration(name, def, inherited[name]))
                out.appendLine()
            }
        }

        out.appendLine("// Hierarchies — every variant the build's profile lists")
        out.appendLine()
        profile.forEach { (name, element) ->
            out.append(hierarchy(name, element.jsonObject, open = name in openHierarchies))
            out.appendLine()
        }
        return out.toString().trimEnd() + "\n"
    }

    private fun hierarchy(
        name: String,
        def: JsonObject,
        open: Boolean,
    ): String {
        val out = StringBuilder()
        val variants = (def["oneOf"]?.jsonArray ?: JsonArray(emptyList())).map { typeOf(it) }
        doc(out, def.description())
        if (open) {
            val unknown = "Unknown$name"
            out.appendLine("export type $name = ${(variants + unknown).joinToString(" | ")};")
            out.appendLine()
            out.appendLine("/** A $name this build does not know — the protocol promises it may arrive (SPEC.md §2.1). */")
            out.appendLine("export interface $unknown {")
            out.appendLine("  type: string;")
            out.appendLine("  [property: string]: unknown;")
            out.appendLine("}")
        } else {
            out.appendLine("export type $name = ${variants.joinToString(" | ").ifEmpty { "never" }};")
        }
        return out.toString()
    }

    private fun declaration(
        name: String,
        def: JsonObject,
        inherited: JsonObject?,
    ): String {
        val out = StringBuilder()
        doc(out, def.description())
        val properties = def["properties"]?.jsonObject
        if (properties == null) {
            out.appendLine("export type $name = ${typeOf(def)};")
            return out.toString()
        }
        val required = def["required"]?.jsonArray?.map { it.jsonPrimitive.content }?.toSet() ?: emptySet()
        // The discriminator is the variant's own; everything else the base declares and the variant does
        // not is added after the variant's properties, always optional.
        val fromBase = (inherited ?: JsonObject(emptyMap())).filterKeys { it !in properties && it != KompotProtocol.DISCRIMINATOR }
        out.appendLine("export interface $name {")
        (properties + fromBase).forEach { (property, schema) ->
            schema.jsonObject.description()?.let { out.appendLine("  /** ${it.replace("*/", "* /")} */") }
            val optional = if (property in required) "" else "?"
            out.appendLine("  ${key(property)}$optional: ${typeOf(schema)};")
        }
        out.appendLine("}")
        return out.toString()
    }

    private fun typeOf(element: JsonElement): String {
        val schema = element as? JsonObject ?: return "unknown"
        schema["\$ref"]?.jsonPrimitive?.content?.let { return it.substringAfterLast("/") }
        schema["const"]?.let { return literal(it) }
        schema["enum"]?.jsonArray?.let { values -> return values.joinToString(" | ") { literal(it) } }
        (schema["oneOf"] ?: schema["anyOf"])?.jsonArray?.let { options -> return options.joinToString(" | ") { typeOf(it) }.distinctUnion() }

        val types =
            when (val t = schema["type"]) {
                is JsonArray -> t.map { it.jsonPrimitive.content }
                is JsonPrimitive -> listOf(t.content)
                else -> return "unknown"
            }
        return types.joinToString(" | ") { single(it, schema) }
    }

    private fun single(
        type: String,
        schema: JsonObject,
    ): String =
        when (type) {
            "string" -> "string"
            "integer", "number" -> "number"
            "boolean" -> "boolean"
            "null" -> "null"
            "array" -> {
                val item = schema["items"]?.let { typeOf(it) } ?: "unknown"
                if (" | " in item) "($item)[]" else "$item[]"
            }
            "object" ->
                when (val additional = schema["additionalProperties"]) {
                    is JsonObject -> "Record<string, ${typeOf(additional)}>"
                    else -> "Record<string, unknown>"
                }
            else -> "unknown"
        }

    private fun literal(value: JsonElement): String =
        when (value) {
            is JsonNull -> "null"
            is JsonPrimitive -> if (value.isString) "\"${value.content.replace("\"", "\\\"")}\"" else value.content
            else -> "unknown"
        }

    private fun key(name: String): String = if (Regex("[A-Za-z_$][A-Za-z0-9_$]*").matches(name)) name else "\"$name\""

    private fun String.distinctUnion(): String = split(" | ").distinct().joinToString(" | ")

    private fun JsonObject.kind(): String? = this["x-kompot-kind"]?.jsonPrimitive?.content

    private fun JsonObject.description(): String? = this["description"]?.jsonPrimitive?.content

    private fun doc(
        out: StringBuilder,
        text: String?,
    ) {
        if (text != null) out.appendLine("/** ${text.replace("*/", "* /")} */")
    }
}
